apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    owner: "Praparn_L"
    version: "1.0"
    module: "Web"
    environment: "development"
spec:
  selector:
    name: web
    owner: "Praparn_L"
    version: "1.0"
    module: "web"
    environment: "development"
  type: NodePort
  ports:
   - port: 5000
     name: webservice
     targetPort: 5000
     protocol: TCP
     nodePort: 32500
   - port: 80
     name: webcache
     targetPort: 80
     protocol: TCP
     nodePort: 30500
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    owner: "Praparn_L"
    version: "1.0"
    module: "web"
    environment: "development"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
        owner: "Praparn_L"
        version: "1.0"
        module: "web"
        environment: "development"
    spec:
      containers:
      - name: cachedb
        image: labdocker/redis:latest
        ports:
        - containerPort: 6379
          protocol: TCP
      - name: webservice
        image: labdocker/cluster:webservice
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: webmodule-configmap
              key: REDIS_HOST
        - name: username
          valueFrom:
            secretKeyRef:
              name: databasemodule-secret
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: databasemodule-secret
              key: password
        ports:
          - containerPort: 5000
            protocol: TCP
      - name: webcache
        image: labdocker/cluster:webcache_kubernetes
        ports:
          - containerPort: 80
            protocol: TCP
